name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }}; Symfony ${{ matrix.symfony }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
        symfony: ['5', '6', '7', '8']
        exclude:
          - php: '7.4'
            symfony: '6'
          - php: '7.4'
            symfony: '7'
          - php: '7.4'
            symfony: '8'
          - php: '8.0'
            symfony: '6'
          - php: '8.0'
            symfony: '7'
          - php: '8.0'
            symfony: '8'
          - php: '8.1'
            symfony: '7'
          - php: '8.1'
            symfony: '8'
          - php: '8.2'
            symfony: '8'
          - php: '8.3'
            symfony: '8'
          - php: '8.5'
            symfony: '5'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 122

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
        env:
          update: true

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Select Symfony 5
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "symfony/filesystem:^5.4" "symfony/process:^5.4" "symfony/var-dumper:^5.4" --dev --no-update --no-interaction
        if: "matrix.symfony == '5'"

      - name: Select Symfony 6
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "symfony/filesystem:^6.0" "symfony/process:^6.0" "symfony/var-dumper:^6.0" --dev --no-update --no-interaction
        if: "matrix.symfony == '6'"

      - name: Select Symfony 7
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "symfony/filesystem:^7.0" "symfony/process:^7.0" "symfony/var-dumper:^7.0" --dev --no-update --no-interaction
        if: "matrix.symfony == '7'"

      - name: Select Symfony 8
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "symfony/filesystem:^8.0" "symfony/process:^8.0" "symfony/var-dumper:^8.0" --dev --no-update --no-interaction
        if: "matrix.symfony == '8'"

      - name: Install Dependencies
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Execute PHPUnit
        run: vendor/bin/phpunit
        env:
          CHROME_PATH: /opt/hostedtoolcache/setup-chrome/chromium/122.0.6261.128/x64/chrome
          CHROME_NO_SANDBOX: true
